{{- if .Values.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "charts.imagePullSecret.dockerconfigjson" . }}
{{- end -}}
