apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.traits.fullname" . }}
  labels:
    {{- include "charts.traits.labels" . | nindent 4 }}
spec:
  type: {{ .Values.traits.service.type }}
  ports:
    - port: {{ .Values.traits.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "charts.traits.selectorLabels" . | nindent 4 }}
