{{- if .Values.traits.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "charts.traits.serviceAccountName" . }}
  labels:
    {{- include "charts.traits.labels" . | nindent 4 }}
  {{- with .Values.traits.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
